### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by DaRealMonika** [V-Blackbird/MindustryJavaTestModv7#1]
i can't download this mod via mod browser or github actions and i really try this

**Comment by V-Blackbird** [comment]
Because Anuke broke the servers where the libraries needed by the compiler are downloaded from. Besides, the mod is still in such a production phase that it is impossible for it to work.

**Comment by V-Blackbird** [comment]
Like my other repos

**Comment by V-Blackbird** [comment]
Sorry, the problem was with the build.gradle. But the mod doesn't really exist anyway.
